@startuml
'https://plantuml.com/sequence-diagram
'図に表示する要素を定義'
actor User as ユーザー
participant ブラウザ
participant Server as サーバー

'処理に連番を自動付与'
autonumber

'noteで図の中にコメントを付与'
'シングルクォートで図には反映されないコメントを書ける'
note over ユーザー
ユーザー -> ブラウザ: ログイン情報を渡す

'直線の矢印は ->。 直線はリクエストを表す
note over ブラウザ: サーバーに確認してもらう
end note
== Initialization ==

Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

== Repetition ==

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml