@startuml

actor Aさん
participant MagicOnion
actor Bさん
actor Cさん

autonumber

Aさん -> MagicOnion:接続(A)
Aさん <- MagicOnion:参加者(A)

MagicOnion <- Bさん:接続(B)
MagicOnion -> Bさん:参加者(A,B)
MagicOnion -> Aさん:通知(B)

MagicOnion <- Cさん:接続(C)
MagicOnion -> Cさん:参加者(A,B,C)
MagicOnion -> Aさん:通知(C)
MagicOnion -> Bさん:通知(C)

@enduml