@startuml
'https://plantuml.com/sequence-diagram

actor Aさん
participant MagicOnion
actor Bさん
actor Cさん

autonumber
Aさん->MagicOnion:切断
MagicOnion->Bさん:退室者(A)

Bさん->MagicOnion:切断
MagicOnion->Cさん:退室者(A,B)

Cさん->MagicOnion:切断
@enduml